### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by cecyaba** [natanaelDominguez28/mercadoLiebre#1]
1. Cumple con lo requerido
2. Cumple con lo requerido
3. No cumple esta comentado
@media(min-width: 570px){
    
}

/* medidas de pantallas para media queries
576
768
992
1200
*/

/*
.contenedor01{
    width:90%;
    background-color:pink;
    color:black;
}
.contenedor02{
    width:50%;
    background-color:pink;
    color:white;
*/

/*@media(min-width: 576px){
    .contenedor01, contenedor02{
        width: 70%;
        margin:auto;
    }
}
*/
/*@media(min-width: 768px){
    .contenedor01{
        background-color:ligthblue;
        color:black;
    }
    .contenedor02{
        background-color:red;
        color:white;
    }
}
*/
/*@media(min-width: 992px){
    .contenedor01, .contenedor02{
        border: solid black 10px;
    }
}
*/
/*@media(min-width: 1200px){
    .contenedor01, contenedor02{
        max-width: 1100px
    }
}
*/
4. Cumple con lo requerido
5. Cumple con lo requerido
6. Cumple con lo requerido
7. No cumple
Tiene un botton
8. Cumple con lo requerido
9. Excelente prolijidad al programar

**Comment by natadominguez** [comment]
corregido item 3

**Comment by natadominguez** [comment]
coregido item 7

**Comment by natadominguez** [comment]
se corrigieron los items 3 y 7, que correspondían a las resoluciones de pantalla y hacer del searchbar un formulario.
